namespace Buildi.Primitives.Banking;

/// <summary>
/// Known Swedish banks, identified by clearing number ranges.
/// </summary>
public enum SwedishBank
{
    Unknown = 0,
    SverigesRiksbank,
    Nordea,
    NordeaPersonkonto,
    NordeaPlusgirot,
    DanskeBank,
    Handelsbanken,
    SEB,
    Swedbank,
    Lansforsakringar,
    IcaBanken,
    Skandiabanken,
    SBABBank,
    AvanzaBank,
    AionBank,
    BnpParibas,
    CitibankEurope,
    HSBBank,
    CalyonBank,
    RoyalBankOfScotland,
    DNBSverige,
    Ekobanken,
    EnityBankGroup,
    EpBank,
    IkanoBank,
    JAKMedlemsbank,
    KlarnaBank,
    LandshypotekBank,
    LunarBank,
    LanOchSparBank,
    MarginalenBank,
    MultitudeBank,
    NobaBankGroup,
    NordnetBank,
    NorthmillBank,
    ResursBank,
    Santander,
    SparbankenSyd,
    SveaBank,
    Alandsbanken,
    VolvofinansBank,
    StadshypotekBank,
    GjensidigeNorSparebank,
    ParetoOhman,
    Forex,
    ParexBank,
    BriteAb,
    BankingCircle,
    BankOfChinaLuxembourg,
    MedMeraBank,
    Folkia,
    NetfondsBank,
    NasdaqOmx,
    Riksgalden,
    Privatgirot,
    Intergiro,
    Nykredit,
    TellerBranchNorway,
    BankernasAutomatbolag,
    TellerBranchSweden,
    KortacceptNordic,
    Kommuninvest,
    VpSecurities
}
